# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Poc

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  print:
    name: "printtttt"
    runs-on: ubuntu-latest
    steps:
      - name: printing something
        run: echo "Hey there! I hope you are doing well"

  build:
    runs-on: ubuntu-latest
    needs: print
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Installing dependencies
      run: npm ci
    - run: npm run build --if-present
    - name: "Running test"
      run: npm test
   
